config/routes.rb
Rails.application.routes.draw do
  resources :advertisments

  resources :thumbnails

 devise_for :users, :skip => [:registrations]                                          
       

  get 'site/index', path: "home"

  get 'site/about', path: "about"

  get 'site/news', path: "news"
  
  get 'site/show',path: "show"

   root 'site#index'

end

app/models/advertisment.rb
class Advertisment < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :thumbnail
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
	has_many :posts, :dependent => :destroy
	accepts_nested_attributes_for :posts, :allow_destroy => true
	mount_uploader :thumb_image, ImageUploader
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :thumbnails, :dependent => :destroy
  has_many :advertisments, :dependent => :destroy

end

app/controllers/advertisments_controller.rb
class AdvertismentsController < ApplicationController
  before_action :set_advertisment, only: [:show, :edit, :update, :destroy]

  # GET /advertisments
  # GET /advertisments.json
  def index
    @advertisments = Advertisment.all
  end

  # GET /advertisments/1
  # GET /advertisments/1.json
  def show
  end

  # GET /advertisments/new
  def new
    @advertisment = Advertisment.new
  end

  # GET /advertisments/1/edit
  def edit
  end

  # POST /advertisments
  # POST /advertisments.json
  def create
    @advertisment = current_user.advertisments.build(advertisment_params)

    respond_to do |format|
      if @advertisment.save
        format.html { redirect_to advertisments_path, notice: 'Advertisment was successfully created.' }
        format.json { render :show, status: :created, location: @advertisment }
      else
        format.html { render :new }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisments/1
  # PATCH/PUT /advertisments/1.json
  def update
    respond_to do |format|
      if @advertisment.update(advertisment_params)
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisment }
      else
        format.html { render :edit }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisments/1
  # DELETE /advertisments/1.json
  def destroy
    @advertisment.destroy
    respond_to do |format|
      format.html { redirect_to advertisments_url, notice: 'Advertisment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisment
      @advertisment = Advertisment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisment_params
      params.require(:advertisment).permit(:image, :say)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :description)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :set_ads, only:[:index, :show, :news, :about]
  def index
    
  	@thumbnails = Thumbnail.order("created_at DESC").paginate(page: params[:page],per_page: 4)
  	
  end
  def set_ads
    @advertisments = Advertisment.all
  end
  def about
  end


  def show
  	@thumbnail = Thumbnail.find(params[:thumbnail_id])
  	@news = Thumbnail.last(5)
  end

  def news
    @thumbnails = Thumbnail.order("created_at DESC").paginate(page: params[:page],per_page: 15)
  end
end

app/controllers/thumbnails_controller.rb
class ThumbnailsController < ApplicationController
  before_action :set_thumbnail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :unless => proc {|c| c.devise_controller?}
  # GET /thumbnails
  # GET /thumbnails.json
  def index
    @thumbnails = Thumbnail.all
  end

  # GET /thumbnails/1
  # GET /thumbnails/1.json
  def show
  end

  # GET /thumbnails/new
  def new
    @thumbnail = Thumbnail.new
  end

  # GET /thumbnails/1/edit
  def edit
  end

  # POST /thumbnails
  # POST /thumbnails.json
  def create
    @thumbnail = current_user.thumbnails.new(thumbnail_params)

    respond_to do |format|
      if @thumbnail.save
        format.html { redirect_to thumbnails_path, notice: 'Thumbnail was successfully created.' }
        format.json { render :show, status: :created, location: @thumbnail }
      else
        format.html { render :new }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thumbnails/1
  # PATCH/PUT /thumbnails/1.json
  def update
    respond_to do |format|
      if @thumbnail.update(thumbnail_params)
        format.html { redirect_to @thumbnail, notice: 'Thumbnail was successfully updated.' }
        format.json { render :show, status: :ok, location: @thumbnail }
      else
        format.html { render :edit }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thumbnails/1
  # DELETE /thumbnails/1.json
  def destroy
    @thumbnail.destroy
    respond_to do |format|
      format.html { redirect_to thumbnails_url, notice: 'Thumbnail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thumbnail
      @thumbnail = Thumbnail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thumbnail_params
      params.require(:thumbnail).permit(:thumb_post, :thumb_title, :thumb_image, posts_attributes: [:id, :title, :image, :description, :_destroy])
    end
end

app/helpers/advertisments_helper.rb
module AdvertismentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/thumbnails_helper.rb
module ThumbnailsHelper
end

app/views/advertisments/_form.html.erb
<%= form_for(@advertisment, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @advertisment.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@advertisment.errors.count, "error") %> prohibited this advertisment from being saved:</h4>

      <ul>
      <% @advertisment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :say, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :say, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/advertisments/edit.html.erb
<div class="page-header">
  <%= link_to advertisments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @advertisment, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing advertisment</h1>
</div>

<%= render 'form' %>

app/views/advertisments/index.html.erb
<div class="page-header mar-t">
<%= render "layouts/msg" %>
  <%= link_to new_advertisment_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Advertisment
  <% end %>
  <h1>ពាណិជ្ជកម្មទាំងអស់</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Image</th>
            <th>Say</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @advertisments) do |advertisment| %>
            <td><%= advertisment.image %></td>
            <td><%= advertisment.say %></td>
            <td><%= link_to 'Show', advertisment %></td>
        <td><%= link_to 'Edit', edit_advertisment_path(advertisment) %></td>
        <td><%= link_to 'Destroy', advertisment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/advertisments/new.html.erb
<div class="page-header mar-t">
<%= render "layouts/msg" %>
  <%= link_to advertisments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New advertisment</h1>
</div>

<%= render 'form' %>

app/views/advertisments/show.html.erb
<div class="page-header">
  <%= link_to advertisments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_advertisment_path(@advertisment), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show advertisment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Image:</dt>
  <dd><%= @advertisment.image %></dd>

  <dt>Say:</dt>
  <dd><%= @advertisment.say %></dd>

</dl>

app/views/layouts/_carousel.erb
 <div class="demo-content">
          <div id="myCarousel" class="carousel slide">
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <!-- Carousel items -->
            <div class="carousel-inner">
              <div class="active item">
                <%= image_tag "logo.jpg" %>
              </div>
               <div class="item">
                <%= image_tag "image-02.JPG" %>
              </div>
              <div class="item">
                <%= image_tag "image-02.JPG" %>
              </div>
              <div class="item">
                <%= image_tag "image-03.JPG" %>
              </div>
            </div>
            <!-- Carousel nav -->
            <a class="carousel-control fui-arrow-left left" href="#myCarousel" data-slide="prev"></a>
            <a class="carousel-control fui-arrow-right right" href="#myCarousel" data-slide="next"></a>
          </div>
</div>
  
  

app/views/layouts/_footer.html.erb
<div class="bottom-menu bottom-menu-inverse" style="margin-top:20px;">
      <div class="container">
        <div class="row">
          <div class="col-md-2 navbar-brand">
            
          </div>

          <div class="col-md-8">
            <ul class="bottom-links">
              <li><a href="#fakelink">About Us</a></li>
              <li><a href="#fakelink">Store</a></li>
              <li class="active"><a href="#fakelink">Jobs</a></li>
              <li><a href="#fakelink">Privacy</a></li>
              <li><a href="#fakelink">Terms</a></li>
              <li><a href="#fakelink">Follow Us</a></li>
              <li><a href="#fakelink">Support</a></li>
              <li><a href="#fakelink">Links</a></li>
            </ul>
          </div>

          <div class="col-md-2">
            <ul class="bottom-icons">
              <li><a href="#fakelink" class="fui-pinterest"></a></li>
              <li><a href="#fakelink" class="fui-facebook"></a></li>
              <li><a href="#fakelink" class="fui-twitter"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="color:#777;">
          <span class="sr-only" style="color:#777;">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "វិទ្យុពាណិជ្ជម្មខេត្តកំពត", root_path, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "ទំព័រ​ដើម", root_path %></li>
          <li><%= link_to "ពត៌មាន", site_news_path %></li>
          <li><%= link_to "អំពី​យើង", site_about_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">

        <% if user_signed_in? %>
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.username%> <b class="caret"></b></a><ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
          <li><%= link_to "បង្កើតអត្ថបទ", new_thumbnail_path%></li>
         <li><%= link_to "បង្ហាញអត្ថបទទាំងអស់", thumbnails_path%></li>
       
         <li class="divider"></li>
          <li><%= link_to 'ពាណិជ្ជកម្ម', new_advertisment_path%></li>
          <li><%= link_to 'ពាណិជ្ជកម្មទាំងអស់', advertisments_path%></li>
        </ul>
        </li>
          <li><%= link_to "ចាកចេញ", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ចូល", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
</div>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>វិទ្យុពាណិជ្ជកម្មខេត្តកំពត</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
      <div class="row">
          <%= yield %>
      </div>
  
  </div>
  <%= render "layouts/footer" %>
    <script type="text/javascript">
      $(document).ready(function(){

        $('.wysihtml5').each(function(i, elem) {
          $(elem).wysihtml5();
        });

     })
    </script>

</body>
</html>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/new.html.erb
<div class="page-header mar-t">
<%= render "layouts/msg" %>
  <%= link_to posts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/site/index.html.erb
<div class="col-lg-8 col-md-8 col-sm-8 mar-t">
<%= render "layouts/msg" %>
<%= render "layouts/carousel" %>
<h5 style="margin-bottom:0px;margin-top:20px;font-family: 'Preahvihear', cursive;">ពត៌មាន​ប្រចាំថ្ងៃ</h5>
<hr style="margin-top:10px;margin-bottom:10px;">
<div class="col-lg-12" style="padding:0px;">
	<% @thumbnails.each do |t| %>
		<%= link_to site_show_path(thumbnail_id: t) do %>
			<div class="col-lg-6">
				<div class="box">
					<div class="box-img"><%= image_tag(t.thumb_image,size: "360x230") %></div>
					<div class="box-title"><%= truncate(t.thumb_title, length: 60) %></div>
				</div>
			</div>	
		<% end %>
	<% end %>
</div>
	<div class="pagination text-centered">
		<%= will_paginate(@thumbnails, renderer: BootstrapPagination::Rails) %>
	</div>
</div>
<%= render 'sidebar' %>

app/views/site/news.html.erb
   <div class="col-lg-8 col-md-8 col-sm-8 mar-t" style="margin-top:60px;">
    <div class="news">
        <h6 style="margin-bottom:8px;">ពត៌មានប្រចាំថ្ងៃ</h6>
        <hr style="margin-top:0px;margin-bottom:10px;">
        <% @thumbnails.each do |thumb| %>
        <div class="col-lg-12">
        <div class="col-lg-6">
            <div class="po-image"><%= image_tag(thumb.thumb_image,size: "300x200")%></div>
        </div>
        <div class="col-lg-6">
            <div class="po-title"><h6><%= thumb.thumb_title %></h6></div>
            <div class="po-desc"><%= truncate( raw( sanitize(thumb.thumb_post, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 180, :omission => "...")%></div>
            <div class="po-desc"><%#= thumb.thumb_post.html_safe %> <%= link_to "អាន​បន្ត", site_show_path(:thumbnail_id => thumb), style: "color:#1c7cb3;" %>      <em style="font-size:14px;float:right;margin-top:3px;">
                    <% if thumb.created_at > Time.now.beginning_of_day %>
                        <%="#{time_ago_in_words(thumb.created_at)} ago"%> 
                    <% else %> 
                        <%= thumb.created_at.strftime("%b %d, %Y") %>
                    <% end %>
                </em> </div>
               <!--  <div class="align-time" style="font-size:12px;float:right;color:#1c7cb3;">
                </div> -->
        </div>
        </div>
        <% end %>

    </div>    
        <div class="pagination text-centered">
        <%= will_paginate(@thumbnails, renderer: BootstrapPagination::Rails) %>
    </div>
</div>
<div style="margin-top:55px;">
<%= render 'sidebar' %>
</div>

app/views/site/show.html.erb
<div>
<div class="show-page mar-t">

<h6><%= @thumbnail.thumb_title %></h6>
	<p style="color:#777;">ផ្សាយដោយ: <%= @thumbnail.user.username %>
		<span>
		<% if @thumbnail.created_at > Time.now.beginning_of_day %>
			<%="#{time_ago_in_words(@thumbnail.created_at)} ago"%> 
		<% else %> 
			<%= @thumbnail.created_at.strftime("%b %d, %Y") %>
		<% end %>

		</span>	
	</p>
<div class="image" style="margin-top:0px;"><%= image_tag(@thumbnail.thumb_image)%></div>	
<div class="desc"><%= @thumbnail.thumb_post.html_safe %></div>
	<% @thumbnail.posts.each do |post|%>	
		<div class="image"><%= image_tag post.image%></div>
		<div class="desc"><%= post.description.html_safe %></div>
	<% end %>
</div> 

<div class="last-news">
	<p>អត្ថបទថ្មីៗ​</p>
	<div class="dialog dialog-info">
		<% @news.each do |n| %>
		<%= link_to site_show_path(post_id: n) do%>
			<ul>
				<span class="glyphicon glyphicon-hand-right"></span> &nbsp;<%= truncate(n.thumb_title,length: 70) %>
				<div class="align-time" style="float:right;">
				<% if n.created_at > Time.now.beginning_of_day %>
					<%="#{time_ago_in_words(n.created_at)} ago"%> 
				<% else %> 
					<%= n.created_at.strftime("%b %d, %Y") %>
				<% end %>
				</div>
			</ul>
		<% end %>
		<% end %>
	</div>
</div>

 <div id="disqus_thread" style="margin-top:30px;"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'peanichakamradio'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span></span> class="logo-disqus">Disqus</span></a>
   </div>

   		<%= render 'sidebar' %>

app/views/thumbnails/_post_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<%= f.label :Image%>
		<br>
		<%= f.text_field :image%><br>
		<br>
		<%= f.label :description%>
		<br>
		<%= f.text_area :description, rows: 4%>
		<%= link_to_remove_association "remove post", f%>
	</div>
</div>

app/views/thumbnails/index.html.erb
<div class="page-header mar-t">
<%= render "layouts/msg" %>
  <%= link_to new_thumbnail_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    បន្ថែម
  <% end %>
  <h1>អត្ថបទទាំងអស់</h1>
</div>


<div class="container-fluid" >
    <div class="container container-pad" id="property-listings">  
      <div class="row">         
            <%= content_tag_for(:tr, @thumbnails) do |thumb| %>
              <div class="col-lg-6"> 
                    <!-- Begin Listing: 609 W GRAVERS LN-->
                    <div class="brdr bgc-fff pad-10 box-shad property-listing">
                        <div class="media">
                            <a class="pull-left" href="#" target="_parent" style="height: auto;">
                            <%=image_tag(thumb.thumb_image)%></a>
                            <div class="clearfix visible-sm"></div>
                            <div class="media-body fnt-smaller">
                                <h4 class="media-heading">
                                  <h6 style="font-size:1em;"><%= truncate(thumb.thumb_title,length: 20)%></h6>
                                </h4>
                                <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
                                    <li><%= link_to "កែប្រែ", edit_thumbnail_path(thumb)%></li>
                                    <li style="list-style: none">|</li>
                                    <li><%= link_to "លុប", thumb, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                                </ul>
                                <p class="hidden-xs"><%= truncate( raw( sanitize(thumb.thumb_post, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 20, :omission => "...", style: "font-size:12px;")%></p>
                            </div>
                        </div>
                  </div>
              </div><!-- End Listing--> 
            <% end %>    
          </div><!-- End Col -->
    </div><!-- End row -->
</div><!-- End container -->

app/views/thumbnails/show.html.erb
<div class="page-header">
  <%= link_to thumbnails_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_thumbnail_path(@thumbnail), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show thumbnail</h1>
</div>

<dl class="dl-horizontal">
  <dt>Thumb post:</dt>
  <dd><%= @thumbnail.thumb_post %></dd>

  <dt>Thumb title:</dt>
  <dd><%= @thumbnail.thumb_title %></dd>

  <dt>Thumb image:</dt>
  <dd><%= @thumbnail.thumb_image %></dd>

</dl>